### PR TITLE
fix: use the correct last wake duration

### PR DESCRIPTION
**Pull request by hi-rustin**
See https://github.com/tokio-rs/console/blob/b158b05df583348c19029c17924b9c898a9e74ef/tokio-console/src/state/tasks.rs#L434

image

### CODE REVIEW

**Review by hi-rustin — COMMENTED** [review]
🔢 Self-check (PR reviewed by myself and ready for feedback.)

**Comment by hi-rustin** [comment]
cc: @suyanhanx 
Could you please take a look? Thanks! 💚 💙 💜 💛 ❤️

Any suggestions are welcome even after I merge it. If you don't have time to review it, that's okay too.

**Comment by hi-rustin** [comment]
I've sent the GitHub invitation to you.

**Review by suyanhanx — APPROVED** [review]
Thank you!

**Comment by suyanhanx** [comment]
> I've sent the GitHub invitation to you.

Thank you! It's my honor.

**Pull request merged**
